name: Autograding

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: education/autograding@v1
